### ISSUE TITLE
Svanill-edit

### ISSUE THREAD

**Issue by STashakkori** [svanill/svanill-cli#1]
Hello and thank you. Where is the source code for svanill-edit? I need to locally change where it points to the svanill binary. It seems to not be able to find it and I think I can fix that on my end pretty quickly. Thanks again

**Comment by STashakkori** [comment]
Oh gosh its a script not a binary. I had the code all along! Wow!

**Comment by riquito** [comment]
> You may want to change the shell to Bash explicitly instead of using sh. I think sh will lead to issues looking at some of the syntax here

Thanks, I'll review it and also run the script through [shellcheck](https://github.com/koalaman/shellcheck) on CI, because sure enough there was a blatant syntax error on master... I symlink the current local branch version to find errors on new code, and I didn't push the fix... so if you tried svanill-edit it should have blown up immediately. I pushed the fix on master https://github.com/svanill/svanill-cli/commit/4aede31bbd3e5ab92b5c5b48179c75da2dcfe1e5
